src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $commandedAt;

    /**
     * @ORM\ManyToMany(targetEntity=Menu::class, inversedBy="commandes")
     */
    private $menus;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="commandes")
     */
    private $client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Etat;

    public function __construct()
    {
        $this->menus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?int
    {
        $menus = $this->getMenus();
        $prix = 0;
        foreach ($menus as $menu) {
            $prix += $menu->getPrix();
        }
        return $prix;
    }

    public function getCommandedAt(): ?\DateTimeImmutable
    {
        return $this->commandedAt;
    }

    public function setCommandedAt(\DateTimeImmutable $commandedAt): self
    {
        $this->commandedAt = $commandedAt;

        return $this;
    }

    /**
     * @return Collection|Menu[]
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        
        $this->menus[] = $menu;
        
        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        $this->menus->removeElement($menu);

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(string $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CommandeRepository;
use App\Entity\Commande;
use App\Entity\Menu;
use App\Repository\MenuRepository;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Doctrine\ORM\EntityManagerInterface;

class CommandeController extends AbstractController
{
    #[Route('/commands', name: 'my_commands')]
    public function index(CommandeRepository $repo): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $user = $this->getUser();
        $commandes=$repo->findby(['client'=>$user]);

        return $this->render('commande/index.html.twig', [
            'controller_name' => 'CommandeController',
            'commandes' => $commandes,
        ]);
    }


    #[Route('/add-command', name: 'make_command')]
    public function makeCommand(MenuRepository $repoM, SessionInterface $session, 
    EntityManagerInterface $em): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $menus = $session->get('panier', []);
        if($menus!=null){
            $commande = new Commande;
            $commande->setEtat("En cours")
                    ->setClient($this->getUser())
                    ->setCommandedAt(new \DateTimeImmutable());
            foreach ($menus as $key=>$menu) {
                $mn = new Menu;
                $mn = $repoM->find($key);
                for ($i=0; $i < $menu ; $i++) { 
                    $commande->addMenu($mn);
                }
            }
            $em->persist($commande);
            $em->flush();
        }else{
            return $this->redirectToRoute('home');
        }
        $session->set('panier', []);
        return $this->redirectToRoute('my_commands');
    }

    #[Route('/edit-commands', name: 'edit_commands')]
    public function dashboard(CommandeRepository $repo): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $user = $this->getUser();
        $commandes=$repo->findAll();

        return $this->render('commande/dashboard.html.twig', [
            'controller_name' => 'CommandeController',
            'commandes' => $commandes,
        ]);
    }

    #[Route('/command/valid/{id}', name: 'valid_command')]
    public function validCommand(Commande $commande, EntityManagerInterface $em): Response{
        if($commande){
            $commande->setEtat('Prete');
            $em->persist($commande);
            $em->flush();
            return $this->redirectToRoute('edit_commands');
        }
    }

    #[Route('/command/cancel/{id}', name: 'cancel_command')]
    public function cancelCommand(Commande $commande,
                                 EntityManagerInterface $em){
        if($commande){
            $commande->setEtat('Annulee');
            $em->persist($commande);
            $em->flush();
            return $this->redirectToRoute('edit_commands');
        }
    }
}

templates/commande/dashboard.html.twig
{% extends 'back.html.twig' %}

{% block page_title %} Commandes {% endblock %}

{% block beadcrumb %} Commandes {% endblock %}

{% block body %}
    <div class='container'>
        <div class="card-body">
                <h5 class="card-title">Commandes <span>| Gérer les commandes effectuées</span></h5>
                <table class="table datatable">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Client</th>
                        <th scope="col">Menus</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Statut</th>
                        <th scope="col">Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for commande in commandes %}
                            <tr>
                                <th scope="row">{{commande.id}}</th>
                                <td>{{commande.client.nomComplet}}</td>
                                <td>
                                    {% for menu in commande.menus %}
                                        {{menu.libelle}}, 
                                    {% endfor %}
                                </td>
                                <td>{{commande.prix}} F CFA</td>
                                <td>
                                    <span 
                                        {% if commande.etat == 'En cours' %}
                                            class="badge bg-warning"
                                        {% elseif commande.etat == 'Prete' %}
                                            class="badge bg-success"
                                        {% else %}
                                            class="badge bg-danger"
                                        {% endif %}
                                        >
                                        {{commande.etat}}
                                    </span>
                                </td>
                                <td>{{commande.commandedAt|date('d-m-Y')}} a {{ commande.commandedAt|date('H:i') }}</td>
                                <td class='d-flex'>
                                    <a type="submit" href="{{path('valid_command', {id:commande.id})}}" class="btn btn-success btn-sm mx-2">
                                        <i class="fas fa-check-square"></i>
                                    </a>
                                    <a type="submit" href="{{path('cancel_command', {id:commande.id})}}" class="btn btn-danger btn-sm mx-2">
                                        <i class="fas fa-window-close"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                </tbody>
                </table>
            </div>
    </div>
{% endblock %}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes commandes!{% endblock %}

{% block body %}
    <div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cart-table-wrap">
						<table class="table">
							<thead class="table-head">
								<tr class="table-head-row">
									<th class="product-image">Menus</th>
									<th class="product-name">Etat</th>
									<th class="product-price">Prix</th>
									<th class="product-quantity">Date</th>
								</tr>
							</thead>
							<tbody>
                                {% for commande in commandes %}
								<tr class='table-body-row'>
                                     <th scope="row" class='text-center'>
										{% for menu in commande.menus %}
                                            {{menu.libelle}} | 
                                        {% endfor %}
									</th>
                                    <td>
										<span 
											{% if commande.etat == 'En cours' %}
												class="badge bg-warning"
											{% elseif commande.etat == 'Prete' %}
												class="badge bg-success"
											{% else %}
												class="badge bg-danger"
											{% endif %}
											>
											{{commande.etat}}
										</span>
									</td>
									<td>{{commande.prix}} Francs CFA</td>
                                    <td>{{commande.commandedAt|date('d-m-Y')}}</td>

                                    
                                </tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}